export const works = [
  {
    id: 1,
    title: 'Social Media App',
    category: 'web',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 2,
    title: 'Rampa UI Design',
    category: 'web',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 3,
    title: 'E-commerce Web Design',
    category: 'web',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 4,
    title: 'Relaweb app Mobile App',
    category: 'web',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 5,
    title: 'Hero Web Design',
    category: 'web',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 6,
    title: 'Banking App',
    category: 'web',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 7,
    title: 'Web Social Media App',
    category: 'Mobile',
    img: 'https://cdn.dribbble.com/users/3967258/screenshots/15463803/media/4fddb9a2caf3b3bd634060f706a91e73.png?compress=1&resize=1200x900',
  },
  {
    id: 8,
    title: 'Web Rampa UI Design',
    category: 'Mobile',
    img: 'https://cdn.dribbble.com/users/3967258/screenshots/15463803/media/4fddb9a2caf3b3bd634060f706a91e73.png?compress=1&resize=1200x900',
  },
  {
    id: 9,
    title: 'Web E-commerce Design',
    category: 'Mobile',
    img: 'https://cdn.dribbble.com/users/3637068/screenshots/15467010/media/69a3279182b75365013fe285733d1122.png?compress=1&resize=1200x900',
  },
  {
    id: 10,
    title: 'Web Relax App',
    category: 'Mobile',
    img: 'https://cdn.dribbble.com/users/2264844/screenshots/15463998/media/d85e92a332c41094f68e1f716884f7ce.jpg?compress=1&resize=1200x900',
  },
  {
    id: 11,
    title: 'Web Design',
    category: 'Mobile',
    img: 'https://cdn.dribbble.com/users/387658/screenshots/15458608/media/e92ec1dd33dd1170ae3dc9c5272f2693.jpg?compress=1&resize=1200x900',
  },
  {
    id: 12,
    title: 'Web Banking App',
    category: 'Mobile',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 13,
    title: 'Design Social Media App',
    category: 'wordpress',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 14,
    title: 'Design Rampa UI Design',
    category: 'wordpress',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 15,
    title: 'Design E-commerce Web Design',
    category: 'wordpress',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 16,
    title: 'Design Relax Mobile App',
    category: 'wordpress',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 17,
    title: 'Design Keser Web Design',
    category: 'wordpress',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
  {
    id: 18,
    title: 'Design Banking App',
    category: 'wordpress',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKvdHn8GmPGCO0y3SJqNHACygpm0h9VycMHg&usqp=CAU',
  },
];

// const menu = [
//     {
//       id: 1,
//       title: "Social Media App",
//       category: 'featuredPortfolio',
//       price: 15.99,
//       img: './images/item-1.jpeg',
//       desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
//     },
//     {
//       id: 2,
//       title: 'diner double',
//       category: 'lunch',
//       price: 13.99,
//       img: './images/item-2.jpeg',
//       desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
//     },
//     {
//       id: 3,
//       title: 'godzilla milkshake',
//       category: 'shakes',
//       price: 6.99,
//       img: './images/item-3.jpeg',
//       desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
//     },
//     {
//       id: 4,
//       title: 'country delight',
//       category: 'featuredPortfolio',
//       price: 20.99,
//       img: './images/item-4.jpeg',
//       desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
//     },
//     {
//       id: 5,
//       title: 'egg attack',
//       category: 'lunch',
//       price: 22.99,
//       img: './images/item-5.jpeg',
//       desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
//     },
//     {
//       id: 6,
//       title: 'oreo dream',
//       category: 'shakes',
//       price: 18.99,
//       img: './images/item-6.jpeg',
//       desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
//     },
//     {
//       id: 7,
//       title: 'bacon overflow',
//       category: 'featuredPortfolio',
//       price: 8.99,
//       img: './images/item-7.jpeg',
//       desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
//     },
//     {
//       id: 8,
//       title: 'american classic',
//       category: 'lunch',
//       price: 12.99,
//       img: './images/item-8.jpeg',
//       desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
//     },
//     {
//       id: 9,
//       title: 'quarantine buddy',
//       category: 'shakes',
//       price: 16.99,
//       img: './images/item-9.jpeg',
//       desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
//     },
//   ];
//   export default menu;
